zstd: extend executeSimple with history support
klauspost/compress pull request #542
Opened 2022-03-24 09:35 UTC by WojciechMula

Add history support in the asm implementation.

As usual marking as a draft, because of few failing tests.

2022-03-24 10:01 UTC, klauspost commented
"Regressions" seems within margin of error. Good job, I will go through it.

2022-03-24 11:40 UTC, WojciechMula commented
Impact of commit https://github.com/klauspost/compress/pull/542/commits/3a351249bf595b30a6dd32f5bb774b0611c5a5a4 (comparison with the previous commit from this branch).

Can't tell it's significantly better or worse, except few cases.

```
benchmark                                                                 old ns/op     new ns/op     delta
BenchmarkDecoder_DecoderSmall/kppkn.gtb.zst-16                            3275140       3197659       -2.37%
BenchmarkDecoder_DecoderSmall/geo.protodata.zst-16                        688157        688801        +0.09%
BenchmarkDecoder_DecoderSmall/plrabn12.txt.zst-16                         10174938      9977297       -1.94%
BenchmarkDecoder_DecoderSmall/lcet10.txt.zst-16                           7464937       7488839       +0.32%
BenchmarkDecoder_DecoderSmall/asyoulik.txt.zst-16                         2315824       2322484       +0.29%
BenchmarkDecoder_DecoderSmall/alice29.txt.zst-16                          2971254       2984982       +0.46%
BenchmarkDecoder_DecoderSmall/html_x_4.zst-16                             1218236       1199092       -1.57%
BenchmarkDecoder_DecoderSmall/paper-100k.pdf.zst-16                       204441        203376        -0.52%
BenchmarkDecoder_DecoderSmall/fireworks.jpeg.zst-16                       126309        126411        +0.08%
BenchmarkDecoder_DecoderSmall/urls.10K.zst-16                             9711496       9721413       +0.10%
BenchmarkDecoder_DecoderSmall/html.zst-16                                 729087        731648        +0.35%
BenchmarkDecoder_DecoderSmall/comp-data.bin.zst-16                        69411         69318         -0.13%
BenchmarkDecoder_DecodeAll/kppkn.gtb.zst-16                               401512        404052        +0.63%
BenchmarkDecoder_DecodeAll/geo.protodata.zst-16                           83962         83687         -0.33%
BenchmarkDecoder_DecodeAll/plrabn12.txt.zst-16                            1155677       1168934       +1.15%
BenchmarkDecoder_DecodeAll/lcet10.txt.zst-16                              860139        873312        +1.53%
BenchmarkDecoder_DecodeAll/asyoulik.txt.zst-16                            299327        301737        +0.81%
BenchmarkDecoder_DecodeAll/alice29.txt.zst-16                             375086        380545        +1.46%
BenchmarkDecoder_DecodeAll/html_x_4.zst-16                                228614        228758        +0.06%
BenchmarkDecoder_DecodeAll/paper-100k.pdf.zst-16                          21867         21759         -0.49%
BenchmarkDecoder_DecodeAll/fireworks.jpeg.zst-16                          11299         11300         +0.01%
BenchmarkDecoder_DecodeAll/urls.10K.zst-16                                1107666       1099319       -0.75%
BenchmarkDecoder_DecodeAll/html.zst-16                                    93401         93670         +0.29%
BenchmarkDecoder_DecodeAll/comp-data.bin.zst-16                           8788          8786          -0.02%
BenchmarkDecoder_DecodeAllFiles/Mark.Twain-Tom.Sawyer.txt/fastest-16      933956        940400        +0.69%
BenchmarkDecoder_DecodeAllFiles/Mark.Twain-Tom.Sawyer.txt/default-16      904977        908869        +0.43%
BenchmarkDecoder_DecodeAllFiles/Mark.Twain-Tom.Sawyer.txt/better-16       857884        864611        +0.78%
BenchmarkDecoder_DecodeAllFiles/Mark.Twain-Tom.Sawyer.txt/best-16         902840        959689        +6.30%
BenchmarkDecoder_DecodeAllFiles/e.txt/fastest-16                          9180          9194          +0.15%
BenchmarkDecoder_DecodeAllFiles/e.txt/default-16                          218821        217876        -0.43%
BenchmarkDecoder_DecodeAllFiles/e.txt/better-16                           186824        186077        -0.40%
BenchmarkDecoder_DecodeAllFiles/e.txt/best-16                             152161        150956        -0.79%
BenchmarkDecoder_DecodeAllFiles/fse-artifact3.bin/fastest-16              3326          3268          -1.74%
BenchmarkDecoder_DecodeAllFiles/fse-artifact3.bin/default-16              3008          2954          -1.80%
BenchmarkDecoder_DecodeAllFiles/fse-artifact3.bin/better-16               3917          3958          +1.05%
BenchmarkDecoder_DecodeAllFiles/fse-artifact3.bin/best-16                 10700         10746         +0.43%
BenchmarkDecoder_DecodeAllFiles/gettysburg.txt/fastest-16                 4753          4665          -1.85%
BenchmarkDecoder_DecodeAllFiles/gettysburg.txt/default-16                 7352          7277          -1.02%
BenchmarkDecoder_DecodeAllFiles/gettysburg.txt/better-16                  7367          7333          -0.46%
BenchmarkDecoder_DecodeAllFiles/gettysburg.txt/best-16                    7250          7770          +7.17%
BenchmarkDecoder_DecodeAllFiles/html.txt/fastest-16                       59693         60146         +0.76%
BenchmarkDecoder_DecodeAllFiles/html.txt/default-16                       61358         61251         -0.17%
BenchmarkDecoder_DecodeAllFiles/html.txt/better-16                        57739         57833         +0.16%
BenchmarkDecoder_DecodeAllFiles/html.txt/best-16                          62846         61222         -2.58%
BenchmarkDecoder_DecodeAllFiles/pi.txt/fastest-16                         9191          9209          +0.20%
BenchmarkDecoder_DecodeAllFiles/pi.txt/default-16                         220163        219331        -0.38%
BenchmarkDecoder_DecodeAllFiles/pi.txt/better-16                          183516        182773        -0.40%
BenchmarkDecoder_DecodeAllFiles/pi.txt/best-16                            151235        152682        +0.96%
BenchmarkDecoder_DecodeAllFiles/pngdata.bin/fastest-16                    27742         27312         -1.55%
BenchmarkDecoder_DecodeAllFiles/pngdata.bin/default-16                    31985         31819         -0.52%
BenchmarkDecoder_DecodeAllFiles/pngdata.bin/better-16                     25521         25129         -1.54%
BenchmarkDecoder_DecodeAllFiles/pngdata.bin/best-16                       33093         32938         -0.47%
BenchmarkDecoder_DecodeAllFiles/sharnd.out/fastest-16                     9187          9186          -0.01%
BenchmarkDecoder_DecodeAllFiles/sharnd.out/default-16                     9181          9184          +0.03%
BenchmarkDecoder_DecodeAllFiles/sharnd.out/better-16                      9176          9178          +0.02%
BenchmarkDecoder_DecodeAllFiles/sharnd.out/best-16                        9202          9210          +0.09%
BenchmarkDecoder_DecodeAllFilesP/Mark.Twain-Tom.Sawyer.txt/fastest-16     125946        124304        -1.30%
BenchmarkDecoder_DecodeAllFilesP/Mark.Twain-Tom.Sawyer.txt/default-16     129010        128391        -0.48%
BenchmarkDecoder_DecodeAllFilesP/Mark.Twain-Tom.Sawyer.txt/better-16      118192        117074        -0.95%
BenchmarkDecoder_DecodeAllFilesP/Mark.Twain-Tom.Sawyer.txt/best-16        123044        123888        +0.69%
BenchmarkDecoder_DecodeAllFilesP/e.txt/fastest-16                         1033          1036          +0.29%
BenchmarkDecoder_DecodeAllFilesP/e.txt/default-16                         35850         35520         -0.92%
BenchmarkDecoder_DecodeAllFilesP/e.txt/better-16                          28095         27881         -0.76%
BenchmarkDecoder_DecodeAllFilesP/e.txt/best-16                            18661         18632         -0.16%
BenchmarkDecoder_DecodeAllFilesP/fse-artifact3.bin/fastest-16             614           717           +16.80%
BenchmarkDecoder_DecodeAllFilesP/fse-artifact3.bin/default-16             725           655           -9.70%
BenchmarkDecoder_DecodeAllFilesP/fse-artifact3.bin/better-16              687           639           -7.00%
BenchmarkDecoder_DecodeAllFilesP/fse-artifact3.bin/best-16                983           985           +0.15%
BenchmarkDecoder_DecodeAllFilesP/gettysburg.txt/fastest-16                925           932           +0.70%
BenchmarkDecoder_DecodeAllFilesP/gettysburg.txt/default-16                1362          1372          +0.73%
BenchmarkDecoder_Deco [...]

2022-03-24 13:30 UTC, klauspost commented
So a tricky situation is that we cannot overread from history, since we may get out of the current page.

So we need a "precise" memory copier. I have one for [s2](https://github.com/klauspost/compress/blob/91d9d326ec882f0c3cabffe16a8222fb057c4874/s2/_generate/gen.go#L2107) which can be adapted. It is used for sizes 1->64, but it could be 0 -> 16 so it can be called whenever there is less than 16 bytes left.

Untested, but this should be something like it:

```Go
// func genMemMoveShort
// src and dst may not overlap.
// No registers are updated.
// Length must be 0 -> 16 bytes
func genMemMoveShort(name string, dst, src, length reg.GPVirtual, end LabelRef) {
	Comment("genMemMoveShort")
	AX, CX := GP64(), GP64()
	name += "_memmove_"

	// Only enable if length can be 0.
	if true {
		TESTQ(length, length)
		JEQ(end)
	}

	CMPQ(length, U8(3))
	JB(LabelRef(name + "move_1or2"))
	JE(LabelRef(name + "move_3"))
	CMPQ(length, U8(8))
	JB(LabelRef(name + "move_4through7"))

	//Label(name + "move_8through16")
	MOVQ(Mem{Base: src}, AX)
	MOVQ(Mem{Base: src, Disp: -8, Index: length, Scale: 1}, CX)
	MOVQ(AX, Mem{Base: dst})
	MOVQ(CX, Mem{Base: dst, Disp: -8, Index: length, Scale: 1})
	JMP(end)

	Label(name + "move_1or2")
	MOVB(Mem{Base: src}, AX.As8())
	MOVB(Mem{Base: src, Disp: -1, Index: length, Scale: 1}, CX.As8())
	MOVB(AX.As8(), Mem{Base: dst})
	MOVB(CX.As8(), Mem{Base: dst, Disp: -1, Index: length, Scale: 1})
	JMP(end)

	Label(name + "move_3")
	MOVW(Mem{Base: src}, AX.As16())
	MOVB(Mem{Base: src, Disp: 2}, CX.As8())
	MOVW(AX.As16(), Mem{Base: dst})
	MOVB(CX.As8(), Mem{Base: dst, Disp: 2})
	JMP(end)

	Label(name + "move_4through7")
	MOVL(Mem{Base: src}, AX.As32())
	MOVL(Mem{Base: src, Disp: -4, Index: length, Scale: 1}, CX.As32())
	MOVL(AX.As32(), Mem{Base: dst})
	MOVL(CX.As32(), Mem{Base: dst, Disp: -4, Index: length, Scale: 1})
	JMP(end)
}
```

2022-03-24 13:39 UTC, WojciechMula commented
Right, I will change it.

2022-03-31 07:49 UTC, WojciechMula commented
OK, I used another memory copy routine for history. Updated the main issue with current timings. Still nice improvments for cases with history.

2022-04-04 08:29 UTC, klauspost requested changes
Let's take out this. Then I don't see any problems in merging.

2022-04-04 08:29 UTC, klauspost commented on zstd/seqdec.go
> +
```suggestion
```

2022-04-04 10:52 UTC, merged